### ISSUE TITLE
pnet训练报错

### ISSUE THREAD

**Issue by andyhx** [xiezheng-cs/mtcnn_pytorch#2]
`
Train Epoch: 1 [1473536/1474127 (100%)] Loss: 0.183586  Accuracy: 0.935780
Train Epoch: 1 [227441/1474127 (100%)]  Loss: 0.229168  Accuracy: 0.927273
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 526, in init
    setattr(self, field_name, field_value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 674, in setter
    field_setter(self, new_value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 662, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\internal\type_checkers.py", line 109, in CheckValue
    raise TypeError(message)
TypeError: tensor(0.1918, device='cuda:0', grad_fn=<DivBackward0>) has type <class 'torch.Tensor'>, but expected one of: ((<class 'numbers.Real'>,),)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "training/pnet/train.py", line 56, in <module>
    cls_loss_, box_offset_loss, total_loss, accuracy = trainer.train(epoch)
  File "D:\ubuntu\Project\mtcnn_ms\mtcnn_pytorch\training\pnet\trainer.py", line 89, in train
    self.logger.scalar_summary(tag, value, self.run_count)
  File "D:\ubuntu\Project\mtcnn_ms\mtcnn_pytorch\tools\logger.py", line 22, in scalar_summary
    summary = tf.Summary(value=[tf.Summary.Value(tag=tag, simple_value=value)])
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 528, in init
    _ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 448, in _ReraiseTypeErrorWithFieldName
    six.reraise(type(exc), exc, sys.exc_info()[2])
  File "C:\ProgramData\Anaconda3\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 526, in init
    setattr(self, field_name, field_value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 674, in setter
    field_setter(self, new_value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 662, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\internal\type_checkers.py", line 109, in CheckValue
    raise TypeError(message)
`
请教一下，训练报这样的错误，是由tf 引起的吗，可以屏蔽tf模块吗，还有
1.pnet需要训练多少轮，大概loss与准确达到多少可以停止了，
2.gpu为啥才占300多M，您训练一个epoch大概需要多久呢，为啥我一个epoch需要两个小时以上有问题吗
感谢！

**Comment by zhy520xp** [comment]
他这个工程很搞笑的。明明是pytorch训练，却在loger模块中去引用tensorflow，两个框架相互干扰。不出问题才怪。

**Comment by zhy520xp** [comment]
https://github.com/wujiyang/MTCNN_TRAIN，把这里的代码原封不动拉过来，就敢上github骗星星。你起码明着感谢一下别人的工作吧？给你一个建议，把这个工程下架了。
